import type { Company } from './types'

export const companies: Company[] = [

  {
    id: 'pl-hotel-1',
    name: 'Hotel Odra Premium',
    category: 'Hotel',
    country: 'Poland',
    city: 'Wrocław',
    address: 'ul. Księcia Witolda 21, Wrocław',
    website: 'https://example.com/hotel-odra',
    email: 'manager@hotelodra.example',
    phone: '+48 71 555 18 24',
    rating: 4.6,
    reviews: 412,
    language: 'Polski',
    reason: 'Готель із великою кількістю номерів, конференц-залами та активним потоком гостей.',
    painPoints: ['Плями на кріслах і диванах', 'Потрібна робота між заїздами гостей'],
    offer: 'Безкоштовне тестове очищення одного крісла та оцінка регулярного обслуговування.',
    status: 'New',
    notes: '',
  },
  {
    id: 'pl-office-1',
    name: 'Warsaw Flex Offices',
    category: 'Office',
    country: 'Poland',
    city: 'Warszawa',
    address: 'ul. Prosta 32, Warszawa',
    website: 'https://example.com/warsaw-flex',
    email: 'office@warsawflex.example',
    phone: '+48 22 555 40 12',
    rating: 4.4,
    reviews: 196,
    language: 'Polski',
    reason: 'Коворкінг із сотнями офісних крісел, переговорними кімнатами та постійною ротацією орендарів.',
    painPoints: ['Регулярне очищення офісних крісел', 'Робота у вечірній час або у вихідні'],
    offer: 'Порахувати кількість крісел і запропонувати поетапне очищення без зупинки роботи офісу.',
    status: 'New',
    notes: '',
  },
  {
    id: 'be-hotel-1',
    name: 'Canal House Hotel',
    category: 'Hotel',
    country: 'Belgium',
    city: 'Brugge',
    address: 'Wollestraat 18, Brugge',
    website: 'https://example.com/canal-house',
    email: 'manager@canalhouse.example',
    phone: '+32 50 555 014',
    rating: 4.5,
    reviews: 318,
    language: 'Nederlands',
    reason: 'Велика кількість номерів, активний сайт і високий потік гостей.',
    painPoints: ['Плями на м’яких меблях у номерах', 'Потреба в роботі без закриття готелю'],
    offer: 'Тестове очищення одного номера та план регулярного обслуговування.',
    status: 'New',
    notes: '',
  },
  {
    id: 'de-office-1',
    name: 'Rhein Business Center',
    category: 'Office',
    country: 'Germany',
    city: 'Düsseldorf',
    address: 'Königsallee 61, Düsseldorf',
    website: 'https://example.com/rhein-business',
    email: 'facility@rheinbusiness.example',
    phone: '+49 211 555 2040',
    rating: 4.2,
    reviews: 87,
    language: 'Deutsch',
    reason: 'Бізнес-центр із великою кількістю офісних крісел та переговорних кімнат.',
    painPoints: ['Зношені офісні крісла', 'Потрібна робота у вечірній час'],
    offer: 'Безкоштовна оцінка кількості крісел і поетапне очищення поверхів.',
    status: 'New',
    notes: '',
  },
  {
    id: 'fr-clinic-1',
    name: 'Clinique Saint-Martin',
    category: 'Clinic',
    country: 'France',
    city: 'Lille',
    address: '14 Rue Nationale, Lille',
    website: 'https://example.com/saint-martin',
    email: 'administration@saintmartin.example',
    phone: '+33 3 20 55 19 10',
    rating: 4.7,
    reviews: 154,
    language: 'Français',
    reason: 'Клініка з рецепцією, зонами очікування та високими вимогами до чистоти.',
    painPoints: ['Регулярна дезінфекція м’яких поверхонь', 'Мінімальний запах після очищення'],
    offer: 'Гіпоалергенне очищення з роботою поза прийомними годинами.',
    status: 'New',
    notes: '',
  },
  {
    id: 'nl-auto-1',
    name: 'Northline Auto Group',
    category: 'Car dealership',
    country: 'Netherlands',
    city: 'Eindhoven',
    address: 'Vestdijk 142, Eindhoven',
    website: 'https://example.com/northline-auto',
    email: 'sales@northlineauto.example',
    phone: '+31 40 555 7788',
    rating: 4.4,
    reviews: 226,
    language: 'Nederlands',
    reason: 'Автосалон регулярно готує автомобілі до продажу та видачі клієнтам.',
    painPoints: ['Нерівномірне завантаження власної команди', 'Термінова підготовка салонів авто'],
    offer: 'Пакетна ціна на регулярне очищення салонів перед продажем.',
    status: 'New',
    notes: '',
  },
]
